// src/report.js — Markdown report generator
import fs from 'fs';
import path from 'path';

/**
 * Generate a severity badge for Markdown.
 */
function severityBadge(severity) {
  switch (severity) {
    case 'High':
      return '🔴 High';
    case 'Medium':
      return '🟡 Medium';
    case 'Low':
      return '🟢 Low';
    default:
      return severity;
  }
}

/**
 * Generate a score color indicator.
 */
function scoreIndicator(score) {
  if (score === null || score === undefined) return '⚪ N/A';
  if (score >= 90) return `🟢 ${score}`;
  if (score >= 50) return `🟡 ${score}`;
  return `🔴 ${score}`;
}

/**
 * Generate the full Markdown audit report.
 *
 * @param {string} domain - The domain being audited
 * @param {string} rootUrl - The root URL
 * @param {Array<{name: string, url: string}>} pages - Audited pages
 * @param {Object} lighthouseResults - Map of pageName -> scores
 * @param {Object} screenshotPaths - Map of pageName -> { desktop, mobile }
 * @param {Array} issues - Aggregated issues
 * @param {string} outputDir - Base output directory
 * @returns {string} Path to the generated report
 */
export function generateReport(
  domain,
  rootUrl,
  pages,
  lighthouseResults,
  screenshotPaths,
  issues,
  outputDir
) {
  const now = new Date().toISOString().split('T')[0];
  const lines = [];

  // ── Header ──
  lines.push(`# 🔍 Website Audit Report: ${domain}`);
  lines.push('');
  lines.push(`**Audit Date:** ${now}`);
  lines.push(`**Target URL:** ${rootUrl}`);
  lines.push(`**Pages Audited:** ${pages.length}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Executive Summary ──
  lines.push('## 📋 Executive Summary');
  lines.push('');

  const highCount = issues.filter((i) => i.severity === 'High').length;
  const medCount = issues.filter((i) => i.severity === 'Medium').length;
  const lowCount = issues.filter((i) => i.severity === 'Low').length;

  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| 🔴 High | ${highCount} |`);
  lines.push(`| 🟡 Medium | ${medCount} |`);
  lines.push(`| 🟢 Low | ${lowCount} |`);
  lines.push(`| **Total** | **${issues.length}** |`);
  lines.push('');

  // ── Lighthouse Scores ──
  lines.push('## 🚀 Lighthouse Scores');
  lines.push('');
  lines.push('| Page | Performance | Accessibility | SEO |');
  lines.push('|------|-------------|---------------|-----|');

  for (const page of pages) {
    const scores = lighthouseResults[page.name];
    if (scores) {
      lines.push(
        `| ${page.name} | ${scoreIndicator(scores.performance)} | ${scoreIndicator(scores.accessibility)} | ${scoreIndicator(scores.seo)} |`
      );
    } else {
      lines.push(`| ${page.name} | ⚪ N/A | ⚪ N/A | ⚪ N/A |`);
    }
  }
  lines.push('');

  // ── Key Issues ──
  if (issues.length > 0) {
    lines.push('## ⚠️ Key Issues');
    lines.push('');

    for (const issue of issues) {
      lines.push(`### ${severityBadge(issue.severity)} — ${issue.issue}`);
      lines.push('');
      lines.push(`- **Page:** ${issue.page}`);
      lines.push(`- **Source:** ${issue.source}`);
      lines.push(`- **Recommendation:** ${issue.recommendation}`);
      lines.push('');
    }
  }

  // ── Page Breakdown ──
  lines.push('## 📄 Page Breakdown');
  lines.push('');

  for (const page of pages) {
    lines.push(`### ${page.name}`);
    lines.push('');
    lines.push(`**URL:** ${page.url}`);
    lines.push('');

    // Scores
    const scores = lighthouseResults[page.name];
    if (scores) {
      lines.push(
        `**Scores:** Performance: ${scores.performance}/100 | Accessibility: ${scores.accessibility}/100 | SEO: ${scores.seo}/100`
      );
      lines.push('');
    }

    // Page-specific issues
    const pageIssues = issues.filter((i) => i.page === page.name);
    if (pageIssues.length > 0) {
      lines.push(`#### Issues (${pageIssues.length})`);
      lines.push('');
      for (const issue of pageIssues) {
        lines.push(`- ${severityBadge(issue.severity)}: ${issue.issue}`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // ── Footer ──
  lines.push('');
  lines.push('---');
  lines.push(`*Generated by AuditLab on ${now}*`);

  const reportContent = lines.join('\n');
  const reportPath = path.join(outputDir, 'report.md');
  fs.writeFileSync(reportPath, reportContent, 'utf-8');

  console.log(`[report] Report saved to ${reportPath}`);
  return reportPath;
}
